/*
 * This source file was generated by the Gradle 'init' task
 */
package bcc.javaJostle;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        assertNotNull("app should have a greeting","test");
    }
}
