/*
 * This source file was generated by the Gradle 'init' task
 */
package bcc.javaJostle;
import javax.swing.SwingUtilities;
import java.util.ArrayList;
import java.util.Arrays;
public class App {

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new GameManager();
            }
        });
    }
}
